"use client"

import type { Metadata } from "next";
import {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/dashboard/app-sidebar";
import {
    Sheet, SheetClose,
    SheetContent,
    SheetDescription,
    SheetFooter,
    SheetHeader,
    SheetTitle,
    SheetTrigger
} from "@/components/ui/sheet";
import {Button} from "@/components/ui/button";

import { Headset } from 'lucide-react';
import {Bubble, BubbleContent, BubbleGroup, BubbleReactions} from "@/components/ui/bubble";
import {Field, FieldGroup} from "@/components/ui/field";
import {FieldDescription, FieldLabel} from "@base-ui/react";
import {
    InputGroup,
    InputGroupAddon,
    InputGroupButton,
    InputGroupText,
    InputGroupTextarea
} from "@/components/ui/input-group";
import {Badge} from "@/components/ui/badge";

//
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="relative">
        <SidebarProvider>
            <AppSidebar />
            <main className="w-full">
                {children}

            </main>
        </SidebarProvider>
        </div>
    )
}

